/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/files/extract': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Extract
     * @description Text from a .txt, .md, .docx or .pdf file (up to 5 MB). PDF text comes back cleaned.
     */
    post: operations['extract_v1_files_extract_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description OK when Redis answers and at least one speech worker is alive.
     */
    get: operations['health_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/text/clean': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Clean
     * @description Fix pasted text: quotes, links, markdown symbols, lines broken mid-sentence.
     */
    post: operations['clean_v1_text_clean_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/tts/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Job
     * @description Queue text for speech. Follow it live on `stream_url`, or poll the job.
     */
    post: operations['create_job_v1_tts_jobs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/tts/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Job
     * @description Status, progress and (when done) a fresh download link.
     */
    get: operations['get_job_v1_tts_jobs__job_id__get']
    put?: never
    post?: never
    /**
     * Cancel Job
     * @description Ask the worker to stop. The final status arrives as a `cancelled` event.
     */
    delete: operations['cancel_job_v1_tts_jobs__job_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/voices': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Voices
     * @description Languages and their voices (the first voice is the default), plus speed and pitch ranges.
     */
    get: operations['list_voices_v1_voices_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_extract_v1_files_extract_post */
    Body_extract_v1_files_extract_post: {
      /** File */
      file: string
    }
    /** ErrorBody */
    ErrorBody: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | 'invalid_input'
        | 'too_long'
        | 'quota_exceeded'
        | 'rate_limited'
        | 'busy'
        | 'not_found'
        | 'internal'
      /** Message */
      message: string
    }
    /** ErrorResponse */
    ErrorResponse: {
      error: components['schemas']['ErrorBody']
    }
    /** ExtractOut */
    ExtractOut: {
      /** Characters */
      characters: number
      /** Cleaned */
      cleaned: boolean
      /** Text */
      text: string
    }
    /** HealthOut */
    HealthOut: {
      /**
       * Redis
       * @enum {string}
       */
      redis: 'ok' | 'down'
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded'
      /** Workers */
      workers: number
    }
    /** JobCreate */
    JobCreate: {
      /**
       * Blend Ratio
       * @default 0.5
       */
      blend_ratio: number
      /** Blend Voice */
      blend_voice?: string | null
      /**
       * Lang
       * @description Language code, see /v1/voices
       * @default a
       */
      lang: string
      /**
       * Pitch
       * @default 0
       */
      pitch: number
      /** Pronunciations */
      pronunciations?: components['schemas']['Pronunciation'][]
      /**
       * Speed
       * @default 1
       */
      speed: number
      /**
       * Text
       * @description Text to speak (limit depends on the account)
       */
      text: string
      /**
       * Voice
       * @default af_heart
       */
      voice: string
    }
    /** JobOut */
    JobOut: {
      /** Audio Seconds */
      audio_seconds?: number | null
      /** Error */
      error?: string | null
      /** Estimated Seconds */
      estimated_seconds?: number | null
      /** Id */
      id: string
      /**
       * Progress
       * @default 0
       */
      progress: number
      /** Queue Position */
      queue_position?: number | null
      /**
       * Status
       * @enum {string}
       */
      status: 'queued' | 'running' | 'done' | 'error' | 'cancelled'
      /** Stream Url */
      stream_url: string
      /**
       * Url
       * @description Signed MP3 link, valid for an hour (when done)
       */
      url?: string | null
    }
    /** LanguageOut */
    LanguageOut: {
      /** Code */
      code: string
      /** Default Voice */
      default_voice: string
      /** Name */
      name: string
      /** Preview Text */
      preview_text: string
      /** Voices */
      voices: components['schemas']['VoiceOut'][]
    }
    /** Pronunciation */
    Pronunciation: {
      /** Say */
      say: string
      /** Word */
      word: string
    }
    /** TextIn */
    TextIn: {
      /** Text */
      text: string
    }
    /** TextOut */
    TextOut: {
      /** Text */
      text: string
    }
    /** VoiceOut */
    VoiceOut: {
      /**
       * Gender
       * @enum {string}
       */
      gender: 'female' | 'male'
      /** Grade */
      grade: string | null
      /** Id */
      id: string
      /** Name */
      name: string
    }
    /** VoicesResponse */
    VoicesResponse: {
      /** Languages */
      languages: components['schemas']['LanguageOut'][]
      /**
       * Pitch
       * @default [
       *       -6,
       *       6
       *     ]
       */
      pitch: [number, number]
      /**
       * Speed
       * @default [
       *       0.5,
       *       2
       *     ]
       */
      speed: [number, number]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  extract_v1_files_extract_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_extract_v1_files_extract_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ExtractOut']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  health_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthOut']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthOut']
        }
      }
    }
  }
  clean_v1_text_clean_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TextIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TextOut']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  create_job_v1_tts_jobs_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JobCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobOut']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_job_v1_tts_jobs__job_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobOut']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  cancel_job_v1_tts_jobs__job_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobOut']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Too Many Requests */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_voices_v1_voices_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VoicesResponse']
        }
      }
    }
  }
}
